TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Add dbd files
DBD += kse4980_units.dbd

#----------------------------------------------------

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

