TOP=../..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += kse4980.db
DATA += kse4980.proto

#=======================================
include $(TOP)/configure/RULES
